'use strict';

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'Другое',
      items: [
        { type: 'link', label: 'Карта', href: '/map' },
        { type: 'autogenerated', dirName: 'other' },
      ],
    },
  ],
};

module.exports = sidebars;
