'use strict';

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    { type: 'autogenerated', dirName: '.' },
    { type: 'link', label: 'Карта', href: '/map' },
    { type: 'link', label: 'Полезные ссылки', href: '/other/links' },
  ],
};

module.exports = sidebars;
